# Generated by Django 6.0.5 on 2026-06-02 23:32

import hello.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/', validators=[hello.models.validate_pdf_extension]),
        ),
    ]
